name: build Docker image

on:
  schedule:
    - cron: '14 3 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [http3-client, octave, quiche-client, sinatra-hello]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1.0.2
      - uses: docker/login-action@v1.6.0
        with:
          username: franklinyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.1.0
        with:
          context: ${{ matrix.image }}
          file: ${{ matrix.image }}/Dockerfile
          push: true
          tags: franklinyu/${{ matrix.image }}:latest
          platforms: linux/amd64
